# Utiliser une image officielle de Node.js (LTS ou version souhaitée)
FROM node:22

# Créer un dossier de travail dans le conteneur
WORKDIR /app

# Copier les fichiers package.json et package-lock.json en premier (cache Docker optimisé)
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le reste (src, routes, controllers, etc.)
COPY . .

# Exposer le port utilisé par Express.js
EXPOSE 8000

# Lancer le serveur
CMD ["node", "server.js"]
